
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author HARPREET KAUR
 */
public class Exam extends javax.swing.JFrame {

    int x,y=60;
  String s6;
  
 public  int count=0;
  String ans1="Singleton Class";
  String ans2="Friend constructor";
  String ans3="Derived class pointer cannot point to base class.";
  String ans4="Friend function";
  String ans5="Dynamic binding";
    public Exam() {
        initComponents();
    }
    
    
    public Exam(String s) {
        initComponents();
        s6="Welcome  "+s;
        
        
    }

    
     public void paint(Graphics g)
    {
    super.paint(g);
    Graphics2D g1=(Graphics2D)g;
   Font f=new Font("Serif", Font.BOLD, 30);
   g1.setFont(f);
   
    g1.setColor(Color.red);
    g1.drawString(s6, x, y);
    try
    {      Thread.sleep(10);
    } 
    catch(Exception e){}
    
    
    x=x+1;
    
    if(x>this.getWidth())
    {
    
    x=0;
    }
    
    repaint();
    
    }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        r11 = new javax.swing.JRadioButton();
        r12 = new javax.swing.JRadioButton();
        r13 = new javax.swing.JRadioButton();
        r14 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        r21 = new javax.swing.JRadioButton();
        r22 = new javax.swing.JRadioButton();
        r23 = new javax.swing.JRadioButton();
        r24 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        r31 = new javax.swing.JRadioButton();
        r32 = new javax.swing.JRadioButton();
        r33 = new javax.swing.JRadioButton();
        r34 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        r41 = new javax.swing.JRadioButton();
        r43 = new javax.swing.JRadioButton();
        r42 = new javax.swing.JRadioButton();
        r44 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        r51 = new javax.swing.JRadioButton();
        r52 = new javax.swing.JRadioButton();
        r54 = new javax.swing.JRadioButton();
        r53 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("Q.1  Which of the following type of class allows only one object of it to be created ?  ");

        r11.setText("Virtual Class");
        r11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r11ActionPerformed(evt);
            }
        });

        r12.setText("Abstract Class");
        r12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r12ActionPerformed(evt);
            }
        });

        r13.setText("Singleton Class");
        r13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r13ActionPerformed(evt);
            }
        });

        r14.setText("Friend Class");
        r14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r14ActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Q.2  Which of the following is not a type of constructor ?");

        r21.setText("Copy constructor");
        r21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r21ActionPerformed(evt);
            }
        });

        r22.setText("Friend constructor");
        r22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r22ActionPerformed(evt);
            }
        });

        r23.setText("Default constructor");
        r23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r23ActionPerformed(evt);
            }
        });

        r24.setText("Parameterized constructor");
        r24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r24ActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Q.3  Which of the following statements is correct ?");

        r31.setText("Base class pointer cannot point to derived class.");
        r31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r31ActionPerformed(evt);
            }
        });

        r32.setText("Derived class pointer cannot point to base class.");
        r32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r32ActionPerformed(evt);
            }
        });

        r33.setText("Pointer to derived class cannot be created.");
        r33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r33ActionPerformed(evt);
            }
        });

        r34.setText("Pointer to base class cannot be created.");
        r34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r34ActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Q.4  Which of the following is not the member of class ?");

        r41.setText("Static function");
        r41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r41ActionPerformed(evt);
            }
        });

        r43.setText("Const function");
        r43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r43ActionPerformed(evt);
            }
        });

        r42.setText("Friend function");
        r42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r42ActionPerformed(evt);
            }
        });

        r44.setText("Virtual function");
        r44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r44ActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(51, 0, 255));
        jLabel5.setText("Q.5 Which of the following concepts means determining at runtime what method to invoke ?");

        r51.setText("Data hiding");
        r51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r51ActionPerformed(evt);
            }
        });

        r52.setText("Dynamic Typing");
        r52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r52ActionPerformed(evt);
            }
        });

        r54.setText("Dynamic loading");
        r54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r54ActionPerformed(evt);
            }
        });

        r53.setText("Dynamic binding");
        r53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r53ActionPerformed(evt);
            }
        });

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addComponent(r11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(r12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(r13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(r14))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addComponent(r51)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(r52)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(r53)
                            .addGap(18, 18, 18)
                            .addComponent(r54))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addComponent(r21)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(r22)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(r23)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(r24))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(48, 48, 48)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(r31)
                                .addComponent(r32, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(r33, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(r34, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addComponent(r41)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(r42)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(r43)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(r44)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jButton1)
                        .addGap(26, 26, 26)
                        .addComponent(jButton2)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r11)
                    .addComponent(r12)
                    .addComponent(r13)
                    .addComponent(r14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r21)
                    .addComponent(r22)
                    .addComponent(r23)
                    .addComponent(r24))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(r31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(r32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(r33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(r34)
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r41)
                    .addComponent(r43)
                    .addComponent(r42)
                    .addComponent(r44))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r51)
                    .addComponent(r52)
                    .addComponent(r54)
                    .addComponent(r53))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void r11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r11ActionPerformed
        if(r11.isSelected())
        {
             count=count+1;
        r12.setSelected(false);
        r13.setSelected(false);r14.setSelected(false);
        
       
        
        
        
       }
    }//GEN-LAST:event_r11ActionPerformed

    private void r21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r21ActionPerformed
      if(r21.isSelected())
        {
        r22.setSelected(false);
        r23.setSelected(false);r24.setSelected(false);
        }
    }//GEN-LAST:event_r21ActionPerformed

    private void r22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r22ActionPerformed
      if(r22.isSelected())
        {
            count=count+1;
        r21.setSelected(false);
        r23.setSelected(false);r24.setSelected(false);
        
        }
    }//GEN-LAST:event_r22ActionPerformed

    private void r23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r23ActionPerformed
       if(r23.isSelected())
        {
        r22.setSelected(false);
        r21.setSelected(false);r24.setSelected(false);
        }
    }//GEN-LAST:event_r23ActionPerformed

    private void r24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r24ActionPerformed
        if(r24.isSelected())
        {
        r22.setSelected(false);
        r23.setSelected(false);r21.setSelected(false);
        }
    }//GEN-LAST:event_r24ActionPerformed

    private void r31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r31ActionPerformed
       if(r31.isSelected())
        {
        r32.setSelected(false);
        r33.setSelected(false);r34.setSelected(false);
        }  
    }//GEN-LAST:event_r31ActionPerformed

    private void r32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r32ActionPerformed
        if(r32.isSelected())
        {
            count=count+1;
        r33.setSelected(false);
        r34.setSelected(false);r31.setSelected(false);
        
        } 
    }//GEN-LAST:event_r32ActionPerformed

    private void r33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r33ActionPerformed
        if(r33.isSelected())
        {
        r32.setSelected(false);
        r31.setSelected(false);r34.setSelected(false);
        } 
    }//GEN-LAST:event_r33ActionPerformed

    private void r34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r34ActionPerformed
        if(r34.isSelected())
        {
        r32.setSelected(false);
        r33.setSelected(false);r31.setSelected(false);
        } 
    }//GEN-LAST:event_r34ActionPerformed

    private void r41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r41ActionPerformed
        if(r41.isSelected())
        {
        r42.setSelected(false);
        r43.setSelected(false);r44.setSelected(false);
        } 
    }//GEN-LAST:event_r41ActionPerformed

    private void r43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r43ActionPerformed
        if(r43.isSelected())
        {
        r42.setSelected(false);
        r41.setSelected(false);r44.setSelected(false);
        } 
    }//GEN-LAST:event_r43ActionPerformed

    private void r42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r42ActionPerformed
       if(r42.isSelected())
        {
            count=count+1;
        r41.setSelected(false);
        r43.setSelected(false);r44.setSelected(false);
        
        } 
    }//GEN-LAST:event_r42ActionPerformed

    private void r44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r44ActionPerformed
        if(r44.isSelected())
        {
        r42.setSelected(false);
        r43.setSelected(false);r41.setSelected(false);
        } 
    }//GEN-LAST:event_r44ActionPerformed

    private void r51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r51ActionPerformed
        if(r51.isSelected())
        {
        r52.setSelected(false);
        r53.setSelected(false);r54.setSelected(false);
        } 
    }//GEN-LAST:event_r51ActionPerformed

    private void r52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r52ActionPerformed
        if(r52.isSelected())
        {
        r51.setSelected(false);
        r53.setSelected(false);r54.setSelected(false);
        } 
    }//GEN-LAST:event_r52ActionPerformed

    private void r54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r54ActionPerformed
       if(r54.isSelected())
        {
        r52.setSelected(false);
        r53.setSelected(false);r51.setSelected(false);
        } 
    }//GEN-LAST:event_r54ActionPerformed

    private void r53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r53ActionPerformed
       if(r53.isSelected())
        {
              count=count+1;
        r52.setSelected(false);
        r51.setSelected(false);r54.setSelected(false);
     
        } 
    }//GEN-LAST:event_r53ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int no=count;
this.setVisible(false);
Result obj=new Result(no);
obj.setVisible(true);
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void r12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r12ActionPerformed
        if(r12.isSelected())
        {
        r11.setSelected(false);
        r13.setSelected(false);r14.setSelected(false);
        }
    }//GEN-LAST:event_r12ActionPerformed

    private void r13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r13ActionPerformed
       if(r13.isSelected())
        {
        r12.setSelected(false);
        r11.setSelected(false);r14.setSelected(false);
        }
    }//GEN-LAST:event_r13ActionPerformed

    private void r14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r14ActionPerformed
        if(r14.isSelected())
        {
        r12.setSelected(false);
        r13.setSelected(false);r11.setSelected(false);
        }
    }//GEN-LAST:event_r14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton r11;
    private javax.swing.JRadioButton r12;
    private javax.swing.JRadioButton r13;
    private javax.swing.JRadioButton r14;
    private javax.swing.JRadioButton r21;
    private javax.swing.JRadioButton r22;
    private javax.swing.JRadioButton r23;
    private javax.swing.JRadioButton r24;
    private javax.swing.JRadioButton r31;
    private javax.swing.JRadioButton r32;
    private javax.swing.JRadioButton r33;
    private javax.swing.JRadioButton r34;
    private javax.swing.JRadioButton r41;
    private javax.swing.JRadioButton r42;
    private javax.swing.JRadioButton r43;
    private javax.swing.JRadioButton r44;
    private javax.swing.JRadioButton r51;
    private javax.swing.JRadioButton r52;
    private javax.swing.JRadioButton r53;
    private javax.swing.JRadioButton r54;
    // End of variables declaration//GEN-END:variables
}
